version: '3.8'

services:
  api:
    image: api_image
    build: 
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - api_media_data:/app/media
      - api_alembic:/app/alembic
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL}
    
  database:
    image: postgres:latest
    environment:
      - LOAD_DEV_ENV_FILE=0
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 15s
      timeout: 30s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql
    restart: unless-stopped
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 15s
      retries: 5

volumes:
  db_data:
  api_media_data:
  api_alembic:


      
      